modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="masonry"
version="${file.jarVersion}"
displayName="Mansonry"
logoFile="Mansonry.png"
description='''
A mod that adds more cut stone types
because minecraft wouldn't.
'''
[[dependencies.masonry]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.masonry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.masonry]]
modId = "blueprint"
mandatory = true
versionRange = "[1.18.2-5.3.1,)"
ordering = "BEFORE"
side = "BOTH"